development:
  adapter: postgresql
  encoding: unicode
  database: appblog_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: appblog_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: appblog_production
  pool: 5
  username: postgres
  password: postgres